dm/urls.py
from django.conf.urls import patterns, url

from dm.views import *

urlpatterns = patterns("dm.views",
	url(r'^$', DocumentListView.as_view(), name='dm_document_list'),
	url(r'^document/create/$',
		DocumentCreateView.as_view(),
		name='dm_document_create'
	),
	url(r'^document/edit/(?P<pk>\d+)/$',
		DocumentUpdateView.as_view(),
		name='dm_document_update'
	),
)

wm/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView

from wm.models import Group, Article, SupplierCode
from wm.views import *

urlpatterns = patterns("wm.views",
	url(r'^$',
		ListView.as_view(
			model=Group,
			context_object_name="nodes",
			template_name="wm/group_tree.html"
		),
		name="wm_group_tree"
	),
	url(r'^article/list/$',
		ListView.as_view(
			model=Article,
			paginate_by=20,
			context_object_name="article_list"
		),
		name="wm_article_list"
	),
	url(r'^article/search/$',
		ArticleSearchView.as_view(),
		name="wm_article_search"
	),
	url(r'^article/shortage/$',
		ArticleShortageView.as_view(
	),
		name="wm_article_shortage"
	),
	url(r'^article/detail/(?P<pk>\d+)/$',
		ArticleDetailView.as_view(),
		name="wm_article_detail"
	),
	url(r'^article/offers/(?P<pk>\d+)/$',
		ArticleDetailView.as_view(
			template_name = 'wm/article_offers.html'
		),
		name="wm_article_offers"
	),
	url(r'^article/edit/(?P<pk>\d+)/$',
		ArticleUpdateView.as_view(),
		name="wm_article_edit"
	),
	url(r'^article/create/$',
		ArticleCreateView.as_view(),
		name="wm_article_create"
	),
	url(r'^article/copy/(?P<pk>\d+)/$',
		ArticleCopyView.as_view(),
		name="wm_article_copy"
	),
	url(r'^article/link/(?P<pk>\d+)/$',
		DocumentLinkView.as_view(),
		name="wm_document_link"
	),
	url(r'^article/unlink/(?P<article_pk>\d+)/(?P<document_pk>\d+)/$',
		DocumentUnlinkView.as_view(),
		name="wm_document_unlink"
	),
	url(r'^brand/list/$',
		BrandListView.as_view(),
		name="wm_brand_list"
	),
	url(r'^brand/create/$',
		BrandCreateView.as_view(),
		name="wm_brand_create"
	),
	url(r'^brand/update/(?P<pk>\d+)/$',
		BrandUpdateView.as_view(),
		name="wm_brand_update"
	),
	url(r'^group/create/$',
		GroupCreateView.as_view(),
		name="wm_group_create"
	),
	url(r'^group/stock/(?P<pk>\d+)/$',
		EditGroupStockView.as_view(),
		name="wm_group_stock"
	),
	url(r'^group/edit_articles/(?P<pk>\d+)/$',
		EditGroupArticlesView.as_view(),
		name="wm_group_edit_articles"
	),
	url(r'^group/edit/(?P<pk>\d+)/$',
		GroupUpdateView.as_view(),
		name="wm_group_edit"
	),
	url(r'^group/(?P<pk>\d+)/articles/$',
		GroupArticlesJSONView.as_view(),
		name="wm_group_articles"
	),
	url(r'^stock_report/$',
		StockReportView.as_view(),
		name="wm_stock_report"
	),
	url(r'^count_sheet/$',
		CountSheetView.as_view(),
		name="wm_count_sheet"
	),
	url(r'^scodes/(?P<pk>\d+)/$',
		DetailView.as_view(
			model = Article,
			context_object_name = 'article',
			template_name = 'wm/article_supplier_codes.html'
		),
		name="wm_scode_list"
	),
	url(r'^scodes/(?P<pk>\d+)/create/$',
		SupplierCodeCreateView.as_view(),
		name="wm_scode_create"
	),
	url(r'^scodes/edit/(?P<pk>\d+)/$',
		SupplierCodeEditView.as_view(),
		name="wm_scode_edit"
	),
	url(r'^scodes/delete/(?P<pk>\d+)/$',
		SupplierCodeDeleteView.as_view(),
		name="wm_scode_delete"
	),
)

om/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

import wm.models as wm
import crm.models as crm

class Offer(models.Model):
	article = models.ForeignKey(wm.Article, verbose_name=_("article"))
	company = models.ForeignKey(crm.Company, verbose_name=_("company"))
	created_on = models.DateField(_("created on"), auto_now_add=True)
	expired_on = models.DateField(_("expired on"), null=True, blank=True)
	code = models.CharField(_("offer code"), max_length=50, null=True, blank=True)
	retail_price = models.FloatField(_("retail price"), null=True, blank=True)
	invoice_price = models.FloatField(_("invoice price"), null=True, blank=True)

	class Meta:
		ordering = ["company", "-created_on"]
		verbose_name = _("offer")
		verbose_name_plural = _("offers")

	def __unicode__(self):
		return _("Offer for %s") % self.article

	@property
	def suggested_price(self):
		if self.retail_price is not None:
			return self.retail_price
		elif self.invoice_price is not None:
			return self.invoice_price / 0.6
		return None

class Order(models.Model):
	created_at = models.DateTimeField(_("created at"), auto_now_add=True)
	completed_on = models.DateField(_("completed on"), null=True, blank=True)
	notes = models.CharField(_("notes"), max_length=255, null=True, blank=True)
	private_note = models.CharField(_("private note"), max_length=255, null=True, blank=True)
	company = models.ForeignKey(crm.Company, verbose_name=_("company"))
	created_by = models.ForeignKey(User, verbose_name=_("created by"))

	class Meta:
		ordering = ["-id",]
		verbose_name = _("order")
		verbose_name_plural = _("orders")

	def __unicode__(self):
		return u"%(year)s-%(company)s-%(id)s" % {
			"year": self.created_at.strftime("%y"),
			"company": self.company.id,
			"id": self.id
		}

	@models.permalink
	def get_absolute_url(self):
		return ("om_order_detail", [self.id])

	@property
	def recipient_list(self):
		return self.company.department_set.filter(
			email__isnull=False,
			send_orders=True
		).values_list('email', flat=True)

class OrderItem(models.Model):
	ordered_quantity = models.FloatField(_("ordered quantity"))
	received_quantity = models.FloatField(_("received quantity"), default=0)
	completed_on = models.DateField(_("completed on"), null=True, blank=True)
	estimated_delivery = models.DateField(_("estimated delivery"), null=True, blank=True)
	order = models.ForeignKey(Order, verbose_name=_("order"))
	offer = models.ForeignKey(Offer, verbose_name=_("offer"))

	class Meta:
		ordering = ['-id',]
		verbose_name = _("order line")
		verbose_name_plural = _("order lines")

	def __unicode__(self):
		return unicode(self.id)

	def as_csv(self, template, sep=u","):
		template = template.replace(" ", "")
		fields = template.split(",")
		csv_list = []
		for field in fields:
			if field == "suppliercode":
				try:
					sc = wm.SupplierCode.objects.get(
						article=self.offer.article,
						company=self.offer.company).code
				except models.ObjectDoesNotExist:
					sc = u" "
				csv_list.append(sc)
			elif field == "quantity":
				csv_list.append(unicode(self.ordered_quantity))
		return csv_list

class CartItem(models.Model):
	offer = models.ForeignKey(Offer, verbose_name=_("offer"))
	quantity = models.FloatField(_("quantity"))

	class Meta:
		verbose_name = _("cart item")
		verbose_name_plural = _("cart items")

	def __unicode__(self):
		return unicode(self.id)

class CsvTemplate(models.Model):
	company = models.ForeignKey(crm.Company, verbose_name=_("company"))
	template = models.CharField(_("template"), max_length=255)

	class Meta:
		verbose_name = _("csv template")
		verbose_name_plural = _("csv templates")

	def __unicode__(self):
		return unicode(self.company)

wm/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from mptt.models import MPTTModel, TreeForeignKey

from crm.models import Company
from dm.models import Document

class Brand(models.Model):
	name = models.CharField(_("name"), max_length=50)

	class Meta:
		ordering = ['name',]
		verbose_name = _("brand")
		verbose_name_plural = _("brands")

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return('wm_brand_detail', [self.id])

class Group(MPTTModel):
	name = models.CharField(_("name"), max_length=50)
	parent = TreeForeignKey('self', null=True, blank=True,
		related_name='children')

	class MPTTMeta:
		order_insertion_by = ['name']
	
	class Meta:
		verbose_name = _("group")
		verbose_name_plural = _("groups")

	def __unicode__(self):
		return self.name
	
	@models.permalink
	def get_absolute_url(self):
		return('wm_group_detail', [self.id])

class Article(models.Model):
	code = models.CharField(_("code"), max_length=128)
	description = models.CharField(_("description"), max_length=255)
	measure_unit = models.CharField(_("measure unit"), max_length=10,
		blank=True, null=True)
	packaging = models.PositiveIntegerField(_("standard packaging"), default=1)
	enabled = models.BooleanField(_("enabled"), default=True)
	favorited = models.BooleanField(_("favorited"), default=False)
	brand = models.ForeignKey(Brand, verbose_name=_("brand"), null=True, blank=True)
        weight = models.FloatField(_("weight (kg)"), default=0)
	group = models.ForeignKey(Group, verbose_name=_("group"))
	control_stock = models.BooleanField(_("control stock"), default=False)
	stock = models.PositiveIntegerField(_("stock"), default=0)
	stock_alert = models.PositiveIntegerField(_("stock alert"), default=0)
        stock_updated = models.DateTimeField(_("stock updated at"),
                default=timezone.now(), # default value for migration
                editable=False) 
	price = models.FloatField(_("retail price"), null=True, blank=True)
        price_updated = models.DateTimeField(_("price updated at"),
                default=timezone.now(), #default value for migration
                editable=False)
	stock_value = models.FloatField(_("stock value"), default=0)
        stock_value_updated = models.DateTimeField(_("stock value updated at"),
                default=timezone.now(), #default value for migration
                editable=False)
	documents = models.ManyToManyField(Document,
		blank=True,
		null=True,
		related_name="articles",
		verbose_name=_("documents")
	)

	class Meta:
		ordering = ['-favorited', '-enabled', 'code',]
		unique_together = [('code', 'brand'),]
		verbose_name = _("article")
		verbose_name_plural = _("articles")
	
	def __unicode__(self):
		return self.code

        def __init__(self, *args, **kwargs):
            super(Article, self).__init__(*args, **kwargs)
            self.__original_stock = self.stock
            self.__original_price = self.price
            self.__original_stock_value = self.stock_value

        def save(self, force_insert=False, force_update=False, *args, **kwargs):
            if self.stock != self.__original_stock:
                self.control_stock = True
                self.stock_updated = timezone.now()
            if self.price != self.__original_price:
                self.price_updated = timezone.now()
            if self.stock_value != self.__original_stock_value:
                self.stock_value_updated = timezone.now()
            if not self.enabled:
                self.favorited = False
            super(Article, self).save(force_insert, force_update,
                    *args, **kwargs)
            self.__original_stock = self.stock
            self.__original_price = self.price

	@models.permalink
	def get_absolute_url(self):
		return('wm_article_detail', [self.id])

        def update_stock(self, items=0):
            if not self.control_stock:
                return
            try:
                i = int(items)
            except ValueError:
                i = 0
            self.stock += i
            if self.stock < 0:
                self.stock = 0
            #self.stock_updated = timezone.now()
            self.save()

        @property
        def show_stock_warning(self):
            return (self.stock < self.stock_alert) or not self.control_stock

        def toggle_favorite(self):
            """Mark/unmark an article as favorited. A favorited article should
            be also enabled."""
            self.favorited = not self.favorited
            if self.favorited and not self.enabled:
                self.enabled = True
            self.save()

class SupplierCode(models.Model):
	article = models.ForeignKey(Article, verbose_name=_("article"))
	company = models.ForeignKey(Company, verbose_name=_("company"))
	code = models.CharField(_("code"), max_length=50)

	class Meta:
		unique_together = [('article', 'company'),]
		verbose_name = _("supplier code")
		verbose_name_plural = _("supplier codes")

	def __unicode__(self):
		return self.code

wm/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from wm.models import Article, Group, SupplierCode

class ArticleForm(forms.ModelForm):
	group = forms.ModelChoiceField(queryset=Group.objects.all(),
		widget=forms.HiddenInput)
	description = forms.CharField(
		label = _("Description"),
		widget=forms.Textarea)
	
	class Meta:
		exclude = ['documents', 'stock_updated',]
		model = Article

class ArticleBatchForm(forms.ModelForm):
    group = forms.CharField(widget=forms.HiddenInput)
    description = forms.CharField(
        label = _("Description"),
        widget=forms.Textarea(attrs={'rows': 2})
        )	

    class Meta:
        model = Article
        fields = ['group', 'code', 'description', 'measure_unit',
                'packaging', 'brand', 'stock', 'stock_value',]

class ArticleStockForm(forms.ModelForm):
    code = forms.CharField(widget=forms.HiddenInput)
    description = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Article
        fields = ['code', 'description', 'stock', 'stock_value',]

    def clean_code(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.code
        else:
            return self.cleaned_data['code']

    def clean_description(self):
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            return instance.description
        else:
            return self.cleaned_data['description']

class DocumentLinkForm(forms.Form):
	article = forms.ModelChoiceField(queryset=Article.objects.all(),
		widget=forms.HiddenInput)
	uuid = forms.CharField(label="uuid",
		help_text=_("Paste the uuid of the document.")
		)

class GroupForm(forms.ModelForm):
	parent = forms.ModelChoiceField(queryset=Group.objects.all(),
		widget=forms.HiddenInput)
	
	class Meta:
		model = Group
                fields = '__all__'

class SupplierCodeForm(forms.ModelForm):
	article = forms.ModelChoiceField(queryset=Article.objects.all(),
		widget=forms.HiddenInput)
	
	class Meta:
		model = SupplierCode
                fields = '__all__'

wm/templates/wm/article_form.html
{% extends 'wm/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load mptt_tags %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'vakata-jstree/themes/default/style.min.css' %}" />
<script src="{% static 'vakata-jstree/jstree.min.js' %}"></script>
<script>
$(function() {
	$('#tree').on('changed.jstree', function(e, data) {
		var obj = data.selected;
		/*var li = $('#' + obj[0]);
		alert(li.text().trim());*/
		var group_id = obj[0].substr(5);
		$('#id_group').val(group_id);
	});
});

$(function() {
	$('#tree').jstree({
		"core" : {
			"multiple" : false,
		},
	});
});
</script>

{% endblock %}

{% block title %}{% trans "Edit article" %}{% endblock %}

{% block content %}

<h1>{% trans "Edit article" %}</h1>

<div class="col-md-6">

<div class="panel panel-primary">
<div class="panel-heading">{% trans "Article details" %}</div>
<div id="article_form" class="panel-body">
<form method="POST" action="." class="uniForm">
{% csrf_token %}

<div class="form-group">
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
{{ form|crispy }}
<div class="form-group">
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
</div>
</div>

</div>
<div class="col-md-6">

<div class="panel panel-primary">
<div class="panel-heading">{% trans "Choose a category for the article" %}</div>
<div class="panel-body">
<div id="tree">
<ul>
	{% recursetree nodes %}
		<li id="node_{{ node.id }}"
		{% if node.id == article.group.id %}data-jstree='{"opened":true, "selected": true}'{% endif %}>
			{{ node.name }}
			{% if not node.is_leaf_node %}
				<ul class="children">
					{{ children }}
				</ul>
			{% endif %}
		</li>
	{% endrecursetree %}
</ul>
</div>
</div>
</div>

</div>

{% endblock %}

wm/templates/wm/article_list.html
{% extends "wm/base.html" %}
{% load i18n %}

{% block title %}{% trans "Articles" %}{% endblock %}

{% block content %}

<h1>{% trans "Articles" %}</h1>

<table class="table table-striped table-hover">
<thead>
<tr>
    <th>{% trans "Reference" %}</th>
    <th>{% trans "Brand" %}</th>
    <th>{% trans "Description" %}</th>
	<th>{% trans "Stock" %}</th>
</tr>
</thead>
<tbody>
{% for article in article_list %}
<tr>
    <td><a href="{% url 'wm_article_detail' article.id %}">{{ article.code }}</a></td>
    <td>{{ article.brand|default_if_none:"" }}</td>
    <td>{{ article.description }}</td>
	<td>
	{% if article.control_stock %}
	{{ article.stock }} {{ article.measure_unit }}
	{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="pager">
	<ul>
		{% if page_obj.has_previous %}
		<li>
			<a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
		</li>
		{% endif %}
		{% if page_obj.has_next %}
		<li>
			<a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
		</li>
		{% endif %}
	</ul>
</div>

{% endblock %}

wm/templates/wm/article_offers.html
{% extends "wm/base.html" %}
{% load i18n %}

{% block title %}{{ article.code }}{% endblock %}

{% block content %}

<h1>{% blocktrans %}Offers for {{ article }}{% endblocktrans %}</h1>
<p>
<a href="{% url 'wm_article_detail' article.id %}">{% trans "Go back" %}</a>
</p>

<table class="table table-striped table-hover">
<thead>
<tr>
	<th>{% trans "Supplier" %}</th>
	<th>{% trans "Date" %}</th>
	<th>{% trans "Expires" %}</th>
	<th>{% trans "Code" %}</th>
	<th>{% trans "Retail price" %}</th>
	<th>{% trans "Invoice price" %}</th>
	<th>{% trans "Actions" %}</th>
</tr>
</thead>
<tbody>
{% for offer in article.offer_set.all %}
<tr>
	<td>{{ offer.company }}</td>
	<td>{{ offer.created_on }}</td>
	<td>
	{% if offer.expired_on %}
		{{ offer.expired_on }}
	{% else %}
	<a href="{% url 'om_offer_expire' offer.id %}">{% trans "Expire" %}</a>
	{% endif %}
	</td>
	<td>{{ offer.code }}</td>
	<td>{{ offer.retail_price|floatformat:2 }}</td>
	<td>{{ offer.invoice_price|floatformat:2 }}</td>
	<td><a href="{% url 'om_offer_edit' offer.id %}">{% trans "Edit" %}</a></td>
</td>
{% endfor %}
</tbody>
</table>

{% endblock %}

wm/templates/wm/article_supplier_codes.html
{% extends 'wm/base.html' %}
{% load i18n %}

{% block title %}{% blocktrans with article.code as code %}Supplier codes for {{ code }}{% endblocktrans %}{% endblock %}

{% block content %}
<h1>{% blocktrans with article.code as code %}Supplier codes for {{ code }}{% endblocktrans %}</h1>

<p>
<a href="{% url 'wm_scode_create' article.id %}">{% trans "New supplier code" %}</a>
|
<a href="{% url 'wm_article_detail' article.id %}">{% trans "Return to article" %}</a>
</p>

<table class="table table-stripe table-hover">
<thead>
<th>{% trans "Supplier" %}</th>
<th>{% trans "Code" %}</th>
<th>{% trans "Actions" %}</th>
</thead>
<tbody>
{% for s in article.suppliercode_set.all %}
<tr>
<td>{{ s.company }}</td>
<td>{{ s.code }}</td>
<td>
<a href="{% url 'wm_scode_edit' s.id %}" class="btn btn-primary btn-xs">{% trans "Edit" %}</a>
<a href="{% url 'wm_scode_delete' s.id %}" class="btn btn-danger btn-xs">{% trans "Delete" %}</a>
</td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock %}

wm/templates/wm/base.html
{% extends "site_base.html" %}
{% load i18n %}

{% block wm %}active{% endblock %}

{% block app_menu %}
<ul class="nav nav-pills">
	<li><a href="{% url 'wm_group_tree' %}">{% trans "Categories" %}</a></li>
	<li><a href="{% url 'wm_group_create' %}">{% trans "New category" %}</a></li>
	<li><a href="{% url 'wm_article_list' %}">{% trans "All articles" %}</a></li>
	<li><a href="{% url 'wm_article_create' %}">{% trans "New article" %}</a></li>
	<li><a href="{% url 'wm_brand_list' %}">{% trans "Brands" %}</a></li>
	<li><a href="{% url 'wm_article_shortage' %}">{% trans "Shortages" %}</a></li>
	{% if user.is_staff %}
	<li><a href="{% url 'wm_stock_report' %}">{% trans "Stock" %}</a></li>
	<li><a href="{% url 'wm_count_sheet' %}">{% trans "Count sheet" %}</a></li>
	{% endif %}
<li>
<form method="GET" action="{% url 'wm_article_search' %}">
  <input class="form-control" placeholder="{% trans "Search" %}" type="text" name="q" />
</form>
</li>
</ul>
{% endblock %}

{% block body %}
{% block content %}{% endblock %}

{% endblock %}

wm/templates/wm/brand_form.html
{% extends 'wm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Edit brand" %}{% endblock %}

{% block content %}
<h1>{% trans "Edit brand" %}</h1>

<form method="post" action="">{% csrf_token %}
{{ form|crispy }}
<div>
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>

{% endblock %}

wm/templates/wm/document_link_form.html
{% extends 'wm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Link document" %}{% endblock %}

{% block content %}
<h1>{% trans "Link document" %}</h1>

<form method="post" action="">{% csrf_token %}
{{ form|crispy }}
<div>
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>

{% endblock %}

wm/templates/wm/group_detail.html
{% extends "wm/base.html" %}
{% load i18n %}

{% block title %}{{ group }}{% endblock %}

{% block content %}

<h1>{{ group }}</h1>
<ul>
{% for g in group.path %}
<li><a href="{% url 'wm_group_detail' g.id %}">{{ g }}</a></li>
{% endfor %}
	<ul>
	{% for g in group.children %}
	<li><a href="{% url 'wm_group_detail' g.id %}">{{ g }}</a></li>
	{% endfor %}
	</ul>
</ul>

<p>
<a href="">{% trans "New category" %}</a>
</p>

<table>
<thead>
<tr>
    <th>{% trans "Reference" %}</th>
    <th>{% trans "Brand" %}</th>
    <th>{% trans "Description" %}</th>
</tr>
</thead>
<tbody>
{% for article in group.article_set.all %}
<tr>
    <td><a href="{% url 'wm_article_detail' article.id %}">{{ article.code }}</a></td>
    <td>{{ article.brand|default_if_none:"" }}</td>
    <td>{{ article.description }}</td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock %}

wm/templates/wm/group_form.html
{% extends 'wm/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load mptt_tags %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'vakata-jstree/themes/default/style.min.css' %}" />
<script src="{% static 'vakata-jstree/jstree.min.js' %}"></script>
<script>
$(function() {
	$('#tree').on('changed.jstree', function(e, data) {
		var obj = data.selected;
		/*var li = $('#' + obj[0]);
		alert(li.text().trim());*/
		var group_id = obj[0].substr(5);
		$('#id_parent').val(group_id);
	});
});

$(function() {
	$('#tree').jstree({
		"core" : {
			"multiple" : false,
		},
	});
});
</script>

{% endblock %}

{% block title %}{% trans "Edit category" %}{% endblock %}

{% block content %}

<h1>{% trans "Edit category" %}</h1>

<div class="col-md-6">

<div class="panel panel-primary">
<div class="panel-heading">{% trans "Group details" %}</div>
<div id="group_form" class="panel-body">

<form method="POST" action="." class="uniForm">
{% csrf_token %}

{{ form|crispy }}
<p><input type="submit" value="{% trans "Save" %}" /></p>
</form>
</div>
</div>

</div>
<div class="col-md-6">

<div class="panel panel-primary">
<div class="panel-heading">{% trans "Chose a parent for this category" %}</div>
<div class="panel-body">
<div id="tree">
<ul>
	{% recursetree nodes %}
		<li id="node_{{ node.id }}"
		{% if node.id == group.parent.id %}data-jstree='{"opened":true, "selected": true}'{% endif %}>
			{{ node.name }}
			{% if not node.is_leaf_node %}
				<ul class="children">
					{{ children }}
				</ul>
			{% endif %}
		</li>
	{% endrecursetree %}
</ul>
</div>
</div>
</div>

</div>

{% endblock %}

wm/templates/wm/stock_report.html
{% extends 'wm/pdf_base.html' %}
{% load mptt_tags %}

{% block content %}

<div id="headerContent">
<h1>Informe de inventario a {{ date }}</h1>
</div>

<table repeat=1>
<thead>
<tr>
<th style="width: 20%">Referencia</th>
<th style="width: 10%">Marca</th>
<th>Descripción</th>
<th style="width: 10%">Unidad</th>
<th style="width: 10%">Existencias</th>
</tr>
</thead>
<tbody>

{% recursetree groups %}
<tr>
<td colspan=5>{{ node.get_ancestors|tree_path:" > "}} > {{ node.name }}</td>
</tr>
{% for article in node.article_set.all %}
{% if article.stock > 0 %}
<tr>
<td>{{ article.code }}</td>
<td>{{ article.brand }}</td>
<td>{{ article.description }}</td>
<td>{{ article.measure_unit|default_if_none:"" }}</td>
<td>{{ article.stock }}</td>
</tr>
{% endif %}
{% endfor %}
{% if not node.is_leaf_node %}
{{ children }}
{% endif %}
{% endrecursetree %}
</tbody>
</table>

{% endblock %}