crm/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from crm.models import Company, Group, Department
from crm.views import *

urlpatterns = patterns("crm.views",
    url(r'^$',
		CompanyListView.as_view(),
		name="crm_company_list"
	),
	url(r'^group/list/$',
		GroupListView.as_view(),
		name="crm_group_list"
	),
	url(r'^group/detail/(?P<pk>\d+)/$',
		GroupDetailView.as_view(),
		name="crm_group_detail"
	),
	url(r'^group/edit/(?P<pk>\d+)/$',
		GroupUpdateView.as_view(),
		name="crm_group_edit"
	),
	url(r'^group/create/$',
		GroupCreateView.as_view(),
		name="crm_group_create"
	),
    url(r'^company/detail/(?P<pk>\d+)/$',
		CompanyDetailView.as_view(),
		name="crm_company_detail"
	),
    url(r'^company/edit/(?P<pk>\d+)/$',
		CompanyUpdateView.as_view(),
		name="crm_company_edit"
	),
	url(r'^company/create/$',
		CompanyCreateView.as_view(),
		name="crm_company_create"
	),
	url(r'^company/search/$',
		CompanySearchView.as_view(),
		name="crm_company_search"
	),
	url(r'^company/history/(?P<pk>\d+)/(?P<year>\d+)/$',
		CompanyYearPurchase.as_view(),
		name="crm_purchase_history"
	),
    url(r'^department/detail/(?P<pk>\d+)/$',
		DepartmentDetailView.as_view(),
		name="crm_department_detail"
	),
    url(r'^department/edit/(?P<pk>\d+)/$',
		DepartmentUpdateView.as_view(),
		name="crm_department_edit"
	),
    url(r'^company/add_department/(?P<pk>\d+)/$',
		DepartmentCreateView.as_view(),
		name="crm_department_create"
	),
	##
	## QUOTATION URLS
	##
	url(r'^quotation/create/(?P<pk>\d+)/$',
		QuotationCreateView.as_view(),
		name="crm_quotation_create"
	),
	url(r'^quotation/list/$',
		QuotationListView.as_view(),
		name="crm_quotation_list"
	),
	url(r'^quotation/list/(?P<pk>\d+)$',
		CompanyQuotationListView.as_view(),
		name="crm_companyquotation_list"
	),
	url(r'^quotation/detail/(?P<pk>\d+)/$',
		QuotationDetailView.as_view(),
		name="crm_quotation_detail"
	),
	url(r'^quotation/pdf/(?P<pk>\d+)/$',
		QuotationPdfView.as_view(),
		name="crm_quotation_pdf"
	),
	url(r'^quotation/edit/(?P<pk>\d+)/$',
		QuotationUpdateView.as_view(),
		name="crm_quotation_update"
	),
	url(r'^quotationitem/create/$',
		QuotationItemCreateView.as_view(),
		name="crm_quotationitem_create"
	),
	url(r'^quotationitem/edit/(?P<pk>\d+)/$',
		QuotationItemUpdateView.as_view(),
		name="crm_quotationitem_update"
	),
	url(r'^quotationitem/delete/(?P<pk>\d+)/$',
		QuotationItemDeleteView.as_view(),
		name="crm_quotationitem_delete"
	),
	##
	## CONTRACT URLS
	##
	url(r'^contract/create/(?P<pk>\d+)/$',
		ContractCreateView.as_view(),
		name="crm_contract_create"
	),
	url(r'^contract/list/$',
		ContractListView.as_view(),
		name="crm_contract_list"
	),
	url(r'^contract/list/(?P<pk>\d+)$',
		CompanyContractListView.as_view(),
		name="crm_companycontract_list"
	),
	url(r'^contract/detail/(?P<pk>\d+)/$',
		ContractDetailView.as_view(),
		name="crm_contract_detail"
	),
	url(r'^contract/pdf/(?P<pk>\d+)/$',
		ContractPdfView.as_view(),
		name="crm_contract_pdf"
	),
	url(r'^contract/edit/(?P<pk>\d+)/$',
		ContractUpdateView.as_view(),
		name="crm_contract_update"
	),
	url(r'^contract/signed/(?P<pk>\d+)/$',
		ContractSignedCopyUpload.as_view(),
		name="crm_contract_signed_upload"
	),
	url(r'^contractitem/create/$',
		ContractItemCreateView.as_view(),
		name="crm_contractitem_create"
	),
	url(r'^contractitem/edit/(?P<pk>\d+)/$',
		ContractItemUpdateView.as_view(),
		name="crm_contractitem_update"
	),
	url(r'^contractitem/delete/(?P<pk>\d+)/$',
		ContractItemDeleteView.as_view(),
		name="crm_contractitem_delete"
	),
	url(r'^quotation/tocontract/(?P<pk>\d+)/$',
		QuotationToContractView.as_view(),
		name="crm_quotation_to_contract"
	),
	##
	## PROFORMA URLS
	##
	url(r'^proforma/create/(?P<pk>\d+)/$',
		ProformaCreateView.as_view(),
		name="crm_proforma_create"
	),
	url(r'^proforma/list/$',
		ProformaListView.as_view(),
		name="crm_proforma_list"
	),
	url(r'^proforma/list/(?P<pk>\d+)$',
		CompanyProformaListView.as_view(),
		name="crm_companyproforma_list"
	),
	url(r'^proforma/detail/(?P<pk>\d+)/$',
		ProformaDetailView.as_view(),
		name="crm_proforma_detail"
	),
	url(r'^proforma/pdf/(?P<pk>\d+)/$',
		ProformaPdfView.as_view(),
		name="crm_proforma_pdf"
	),
	url(r'^proforma/edit/(?P<pk>\d+)/$',
		ProformaUpdateView.as_view(),
		name="crm_proforma_update"
	),
	url(r'^proformaitem/create/$',
		ProformaItemCreateView.as_view(),
		name="crm_proformaitem_create"
	),
	url(r'^proformaitem/edit/(?P<pk>\d+)/$',
		ProformaItemUpdateView.as_view(),
		name="crm_proformaitem_update"
	),
	url(r'^proformaitem/delete/(?P<pk>\d+)/$',
		ProformaItemDeleteView.as_view(),
		name="crm_proformaitem_delete"
	),
	##
	## DELIVERY NOTE URLS 
	##
	url(r'^delivery/create/(?P<pk>\d+)/$',
		DeliveryNoteCreateView.as_view(),
		name="crm_deliverynote_create"
	),
	url(r'^delivery/list/$',
		DeliveryNoteListView.as_view(),
		name="crm_deliverynote_list"
	),
	url(r'^delivery/list/company/(?P<pk>\d+)$',
		CompanyDeliveryNoteListView.as_view(),
		name="crm_companydeliverynote_list"
	),
	url(r'^delivery/list/contract/(?P<pk>\d+)$',
		ContractDeliveryNoteListView.as_view(),
		name="crm_contractdeliverynote_list"
	),
	url(r'^delivery/detail/(?P<pk>\d+)/$',
		DeliveryNoteDetailView.as_view(),
		name="crm_deliverynote_detail"
	),
	url(r'^delivery/item/create/$',
		DeliveryNoteItemCreateView.as_view(),
		name="crm_deliverynoteitem_create"
	),
	url(r'^delivery/pdf/(?P<pk>\d+)/$',
		DeliveryNotePdfView.as_view(),
		name="crm_deliverynote_pdf"
	),
)

dm/urls.py
from django.conf.urls import patterns, url

from dm.views import *

urlpatterns = patterns("dm.views",
	url(r'^$', DocumentListView.as_view(), name='dm_document_list'),
	url(r'^document/create/$',
		DocumentCreateView.as_view(),
		name='dm_document_create'
	),
	url(r'^document/edit/(?P<pk>\d+)/$',
		DocumentUpdateView.as_view(),
		name='dm_document_update'
	),
)

crm/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned

from model_utils.managers import PassThroughManager

from crm.defaults import *
from crm import querysets

class Group(models.Model):
	"""
	Group represents a corporate group, that includes more than one company
	"""
	name = models.CharField(_("name"), max_length=50, unique=True)

	class Meta:
		ordering = ['name',]
		verbose_name = _("group")
		verbose_name_plural = _("groups")
		permissions = (('view_group', 'Can view group'),)

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('crm_group_detail', [self.id])

class Company(models.Model):
	name = models.CharField(_("name"), max_length=255, unique=True)
	vatin = models.CharField(_("VATIN"), max_length=16, blank=True, null=True)
	address = models.CharField(_("address"), max_length=255, blank=True,
		null=True)
	city = models.CharField(_("city"), max_length=50, blank=True, null=True)
	region = models.CharField(_("region"), max_length=50, blank=True, null=True)
	postal_code = models.CharField(_("postal code"), max_length=10, blank=True,
		null=True)
	country = models.CharField(_("country"), max_length=50, blank=True,
		null=True)
	comment = models.TextField(_("comment"), blank=True, null=True)
	website = models.URLField(_("website"), max_length=200,
		blank=True, null=True)
	global_email = models.EmailField(_("global email"), max_length=75, blank=True, null=True)
	main_phone = models.CharField(_("main phone"), max_length=40, blank=True, null=True)
	secondary_phone = models.CharField(_("secondary_phone"), max_length=40, blank=True, null=True)
	fax = models.CharField(_("fax"), max_length=40, blank=True, null=True)
	created_at = models.DateTimeField(_("created at"), auto_now_add=True)
	updated_at = models.DateTimeField(_("updated at"), auto_now=True)
	is_customer = models.BooleanField(_(" is customer"), default=False)
	is_supplier = models.BooleanField(_(" is supplier"), default=False)
	group = models.ForeignKey(Group, verbose_name=_("group"), null=True,
		blank=True)

	class Meta:
		ordering = ['name', ]
		verbose_name = _("company")
		verbose_name_plural = _("companies")
		permissions = (('view_company', 'Can view company'),)

	def __unicode__(self):
		return self.name
	
	@models.permalink
	def get_absolute_url(self):
		return ('crm_company_detail', [self.id])

	@property
	def order_emails_list(self):
		return self.department_set.filter(
			email__isnull=False,
			send_orders=True
		).values_list('email', flat=True)

class Customer(Company):
	pass

	class Meta:
		proxy = True
		verbose_name = _("customer")
		verbose_name_plural = _("customers")

class Supplier(Company):
	pass

	class Meta:
		proxy = True
		verbose_name = _("supplier")
		verbose_name_plural = _("suppliers")

class Department(models.Model):
	name = models.CharField(_("name"), max_length=50)
	person = models.CharField(_("person"), max_length=100, blank=True,
		null=True)
	phone = models.CharField(_("phone"), max_length=40, blank=True, null=True)
	email = models.EmailField(_("email"), max_length=75, blank=True, null=True)
	send_orders = models.BooleanField(_("send orders"), default=False)
	comment = models.CharField(_("comment"), max_length=255, blank=True,
		null=True)
	company = models.ForeignKey(Company, null=True, blank=True,
		verbose_name=_("company"))

	class Meta:
		ordering = ['name', ]
		verbose_name = _("department")
		verbose_name_plural = _("departments")
		permissions = (('view_department', 'Can view department'),)

	def __unicode__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('crm_department_detail', [self.id])

class SalesDocument(models.Model):
	company = models.ForeignKey(Company, verbose_name=_("company"))
	author = models.ForeignKey(User, verbose_name=_("author"))
	language = models.CharField(_("language"), max_length=8,
		choices=REPORT_LANGUAGES)
	disaggregated = models.BooleanField(_("disaggregated"), default=True)
	total = models.DecimalField(_("total"), max_digits=12, decimal_places=2,
		blank=True, null=True)

	class Meta:
		abstract = True
		ordering = ['-id',]

	def __unicode__(self):
		return u"%(year)s-%(company)s-%(id)s" % {
			"year": self.created.strftime("%y"),
			"company": self.company.id,
			"id": self.id
		}

class SalesDocumentItem(models.Model):
	quantity = models.PositiveIntegerField(_("quantity"), default=1)
	description = models.TextField(_("description"))
	price = models.DecimalField(_("price"), max_digits=12, decimal_places=2,
		blank=True, null=True)

	class Meta:
		abstract = True

	def __unicode__(self):
		return unicode(self.description)

class Quotation(SalesDocument):
	created = models.DateField(_("created"))
	recipient_name = models.CharField(_("recipient name"), max_length=255,
		blank=True, null=True)
	title = models.CharField(_("title"), max_length=255)
	conditions = models.TextField(_("conditions"), blank=True, null=True)
	private_note = models.CharField(_("private note"), max_length=255,
		blank=True, null=True)

	class Meta(SalesDocument.Meta):
		verbose_name = _("quotation")
		verbose_name_plural = _("quotations")
		permissions = (('view_quotation', 'Can view quotation'),)

	@models.permalink
	def get_absolute_url(self):
		return ('crm_quotation_detail', [self.id])

class QuotationItem(SalesDocumentItem):
	quotation = models.ForeignKey(Quotation, verbose_name=_("quotation"))
	optional = models.BooleanField(_("optional"), default=False)

	objects = PassThroughManager.for_queryset_class(
		querysets.QuotationItemQuerySet)()

	class Meta(SalesDocumentItem.Meta):
		verbose_name = _("quotation item")
		verbose_name_plural = _("quotation items")
	
class Contract(SalesDocument):
	created = models.DateField(_("created"))
	delivery_time = models.TextField(_("delivery time"), default="", blank=True)
	delivery_method = models.CharField(_("delivery method"), max_length=255,
		default="", blank=True)
	conditions = models.TextField(_("conditions"), blank=True, default="")
	remarks = models.TextField(_("remarks"), default="", blank=True)
	vat = models.DecimalField(_("VAT"), max_digits=4, decimal_places=2,
		choices=VAT_CHOICES)
	signed_copy = models.FileField(_("signed copy"), upload_to="crm/contracts",
		blank=True, null=True)

	class Meta(SalesDocument.Meta):
		verbose_name = _("contract")
		verbose_name_plural = _("contracts")
		permissions = (('view_contract', 'Can view contract'),)

	def __unicode__(self):
		return "".join(["C",
			super(Contract, self).__unicode__()]
		)

	@models.permalink
	def get_absolute_url(self):
		return ('crm_contract_detail', [self.id])

class ContractItem(SalesDocumentItem):
	contract = models.ForeignKey(Contract, verbose_name=_("contract"))
	
	objects = PassThroughManager.for_queryset_class(
		querysets.ContractItemQuerySet)()

	class Meta(SalesDocumentItem.Meta):
		verbose_name = _("contract item")
		verbose_name_plural = _("contract items")
	
class Proforma(SalesDocument):
	created = models.DateField(_("created"))
	remarks = models.TextField(_("remarks"), default="", blank=True)
	vat = models.DecimalField(_("VAT"), max_digits=4, decimal_places=2,
		choices=VAT_CHOICES)

	class Meta(SalesDocument.Meta):
		verbose_name = _("proforma")
		verbose_name_plural = _("proformas")
		permissions = (('view_proforma', 'Can view proforma'),)

	def __unicode__(self):
		return "".join(["P",
			super(Proforma, self).__unicode__()]
		)

	@models.permalink
	def get_absolute_url(self):
		return ('crm_proforma_detail', [self.id])

class ProformaItem(SalesDocumentItem):
	proforma = models.ForeignKey(Proforma, verbose_name=_("proforma"))
	
	objects = PassThroughManager.for_queryset_class(
		querysets.ProformaItemQuerySet)()
	
	class Meta(SalesDocumentItem.Meta):
		verbose_name = _("proforma item")
		verbose_name_plural = _("proforma items")
	
class DeliveryNote(models.Model):
	contract = models.ForeignKey(Contract, verbose_name=_("contract"))
	created = models.DateField(_("created"))
	remarks = models.TextField(_("remarks"), default="", blank=True)

	class Meta:
		ordering = ['-id',]
		verbose_name = _("delivery note")
		verbose_name_plural = _("delivery notes")
		permissions = (('view_deliverynote', 'Can view delivery note'),)

	def __unicode__(self):
		return u"A%(year)s-%(company)s-%(id)s" % {
			"year": self.created.strftime("%y"),
			"company": self.contract.company.id,
			"id": self.id
		}

	@models.permalink
	def get_absolute_url(self):
		return ('crm_deliverynote_detail', [self.id])

class DeliveryNoteItem(models.Model):
	note = models.ForeignKey(DeliveryNote, verbose_name=_("delivery note"))
	quantity = models.PositiveIntegerField(_("quantity"), default=1)
	description = models.TextField(_("description"))

	class Meta:
		verbose_name = _("delivery note item")
		verbose_name_plural = _("delivery note items")
	
	def __unicode__(self):
		return unicode(self.id)

crm/templates/crm/base.html
{% extends "site_base.html" %}
{% load i18n %}

{% block crm %}active{% endblock %}

{% block app_menu %}
<ul class="nav nav-pills">
	<li><a href="{% url 'crm_group_list' %}">{% trans "Groups" %}</a></li>
	<li><a href="{% url 'crm_company_list' %}">{% trans "Companies" %}</a></li>
	<li><a href="{% url 'crm_company_create' %}">{% trans "New company" %}</a></li>
	<li class="dropdown">
		<a class="dropdown-toggle" data-toggle="dropdown" href="#">
			{% trans "Documents" %} <span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<li><a href="{% url 'crm_quotation_list' %}">{% trans "Quotations" %}</a></li>
			<li><a href="{% url 'crm_proforma_list' %}">{% trans "Proformas" %}</a></li>
			<li><a href="{% url 'crm_contract_list' %}">{% trans "Contracts" %}</a></li>
			<li><a href="{% url 'crm_deliverynote_list' %}">{% trans "Delivery notes" %}</a></li>
		</ul>
	</li>
<li>
<form method="GET" action="{% url 'crm_company_search' %}">
  <input class="form-control col-lg-8" placeholder="{% trans "Search" %}" type="text" name="q" />
</form>
</li>
</ul>
{% endblock %}

{% block body %}
{% block content %}{% endblock %}

{% endblock %}

crm/templates/crm/company_form.html
{% extends 'crm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Edit company" %}{% endblock %}

{% block content %}

<h1>{% trans "Edit company" %}</h1>

<form method="POST" action=".">
{% csrf_token %}

{{ form|crispy }}

<div class="form-group">

  <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
{% endblock %}

crm/templates/crm/contract_en_pdf.html
{% load staticfiles %}
{% load humanize %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<style type="text/css">
	@page {
		size: A4 portrait;

		@frame header_frame {
			left: 30pt;
			top: 30pt;
			width: 500pt;
			height: 80pt;
			-pdf-frame-content: header_content;
		}

		@frame content_frame {
			left: 30pt;
			top: 120pt;
			width: 500pt;
			height: 650pt;
		}

	}

body {
	font-family: Arial Verdana serif;
	font-size: 12px;
}

h1,h2 {
	text-align: center;
}

p {
	margin: 0.5em;
}

table {
	table-layout: fixed;
	margin-top: 1em;
	margin-bottom: 1em;
}

td,
th {
	border: solid 1px #333;
	padding: 0.2em;
	vertical-align: top;
}

th {
	text-align: center;
}

em {
	font-size: 85%;
}

.currency {
	text-align: right;
	vertical-align: bottom;
}
#info table {
	margin: 0;
	table-layout: auto;
}

#info table th {
	width: 12%;
	border: 0;
	text-align: left;
}

#info table td {
	border: 0;
}

#detail th,
#detail td {
	border-width: 0 0 1px 0;
	padding: 0.4em 0.2em 0em 0.2em;
}

</style>
</head>
<body>

<div id="header_content">
<table>
	<tr>
		<td style="border: 0">
		<img src="{% static 'img/main_logo.png' %}" />
		</td>
		<td style="font-size: small; text-align: right; border:0">
		{{ address|linebreaksbr }}
		</td>
	</tr>
</table>
</div>

<div id="info">
	<table>
		<tr>
		<th>Referencia:</th>
		<td>{{ contract }}</td>
		<th>Fecha:</th>
		<td>{{ contract.created }}</td>
		</tr>
	</table>
	<table>
		<tr>
		<th>Nombre:</th>
		<td>{{ contract.company }}</td>
		<th>NIF/CIF:</th>
		<td>{{ contract.company.vatin }}</td>
		</tr>
	</table>
	<table>
		<tr>
		<th>Domicilio:</th>
		<td>{{ contract.company.address }}</td>
		<th>C.P.:</th>
		<td>{{ contract.company.postal_code }}</td>
		</tr>
	</table>
	<table>
		<tr>
		<th>Localidad:</th>
		<td>{{ contract.company.city }}</td>
		<th>Provincia:</th>
		<td>{{ contract.company.region }}</td>
		<th>País:</th>
		<td>{{ contract.company.country }}</td>
		</tr>
	</table>
</div>

<h1>CONTRATO</h1>

<table id="detail" repeat="1">
	<thead>
	<tr>
		<th style="width:10%">Cant.</th>
		<th>Descripción</th>
		{% if contract.disaggregated %}
		<th style="width: 15%">Precio (€/ud)</th>
		<th style="width: 15%">Importe (€)</th>
		{% endif %}
	</tr>
	</thead>
	<tbody>
	{% for item in contract.contractitem_set.with_total %}
	<tr>
		<td style="text-align: center">{{ item.quantity }}</td>
		<td>{{ item.description }}</td>
		{% if contract.disaggregated %}
		<td class="currency">
		{{ item.price|intcomma }}
		</td>
		<td class="currency">
		{{ item.total|intcomma }}
		</td>
		{% endif %}
	</tr>
	{% endfor %}
	</tbody>
</table>

<table>
<thead>
	<tr>
		<th>Base Imponible:</th>
		<th>% IVA:</th>
		<th>Importe IVA:</th>
		<th>IMPORTE TOTAL:</th>
	</tr>
</thead>
<tbody>
	<tr>
		<td class="currency">{{ total|intcomma }} €</td>
		<td class="currency">{{ contract.vat|intcomma }} %</td>
		<td class="currency">{{ vat_amount|intcomma }} €</td>
		<th class="currency">{{ total_plus_vat|intcomma }} €</th>
	</tr>
</tbody>
</table>


<div>
<h4>Plazo de entrega:</h4>
{{ contract.delivery_time|linebreaks }}
<h4>Forma de envío:</h4>
{{ contract.delivery_method|linebreaks }}
<h4>Condiciones de pago:</h4>
{{ contract.conditions|linebreaks }}
<h4>Observaciones:</h4>
{{ contract.remarks|linebreaks }}
</div>

<div>
<h3>El presente contrato queda sujeto a las condiciones particulares negociadas entre las partes y, en su defecto, a las claúsulas que al dorso se detallan.</h3>
</div>


<div style="font-size: small; border-top: solid 1px black">
{{ disclaimer }}
</div>


</body>
</html>

crm/templates/crm/delivery_es_pdf.html
{% load staticfiles %}
{% load humanize %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<style type="text/css">
	@page {
		size: A4 portrait;

		@frame header_frame {
			left: 30pt;
			top: 30pt;
			width: 500pt;
			height: 80pt;
			-pdf-frame-content: header_content;
		}

		@frame content_frame {
			left: 30pt;
			top: 120pt;
			width: 500pt;
			height: 650pt;
		}

	}

body {
	font-family: Arial Verdana serif;
	font-size: 12px;
}

h1,h2 {
	text-align: center;
}

p {
	margin: 0.5em;
}

table {
	table-layout: fixed;
	margin-top: 1em;
	margin-bottom: 1em;
}

td,
th {
	border: solid 1px #333;
	padding: 0.2em;
	vertical-align: top;
}

th {
	text-align: center;
}

em {
	font-size: 85%;
}

.currency {
	text-align: right;
	vertical-align: bottom;
}
#info table {
	margin: 0;
	table-layout: auto;
}

#info table th {
	width: 12%;
	border: 0;
	text-align: left;
}

#info table td {
	border: 0;
}

#detail th,
#detail td {
	border-width: 0 0 1px 0;
	padding: 0.4em 0.2em 0em 0.2em;
}

</style>
</head>
<body>

<div id="header_content">
<table>
	<tr>
		<td style="border: 0">
		<img src="{% static 'img/main_logo.png' %}" />
		</td>
		<td style="font-size: small; text-align: right; border:0">
		{{ address|linebreaksbr }}
		<br />
		CIF: {{ vat_no }}
		</td>
	</tr>
</table>
</div>

<div id="info">
	<table>
		<tr>
		<th>Referencia:</th>
		<td>{{ note }}</td>
		<th>Fecha:</th>
		<td>{{ note.created }}</td>
		<th>Contrato:</th>
		<td>{{ note.contract }}</td>
		</tr>
	</table>
	<table>
		<tr>
		<th>Nombre:</th>
		<td>{{ note.contract.company }}</td>
		<th>NIF/CIF:</th>
		<td>{{ note.contract.company.vatin }}</td>
		</tr>
	</table>
	<table>
		<tr>
		<th>Domicilio:</th>
		<td>{{ note.contract.company.address }}</td>
		<th>C.P.:</th>
		<td>{{ note.contract.company.postal_code }}</td>
		</tr>
	</table>
	<table>
		<tr>
		<th>Localidad:</th>
		<td>{{ note.contract.company.city }}</td>
		<th>Provincia:</th>
		<td>{{ note.contract.company.region }}</td>
		<th>País:</th>
		<td>{{ note.contract.company.country }}</td>
		</tr>
	</table>
</div>

<h1>ALBARÁN DE ENTREGA</h1>

<table id="detail" repeat="1">
	<thead>
	<tr>
		<th style="width:10%">Cant.</th>
		<th>Descripción</th>
	</tr>
	</thead>
	<tbody>
	{% for item in note.deliverynoteitem_set.all %}
	<tr>
		<td style="text-align: center">{{ item.quantity }}</td>
		<td>{{ item.description }}</td>
	</tr>
	{% endfor %}
	</tbody>
</table>


<div>
<h4>Referencias de maquinaria:</h4>
<p>{{ projects }}
<h4>Observaciones:</h4>
{{ note.remarks|linebreaks }}
</div>

<div>
<h4>Recibí conforme,</h4>
</div>

</body>
</html>

crm/templates/crm/department_form.html
{% extends 'crm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Edit department" %}{% endblock %}

{% block content %}

<h1>{% trans "Edit department" %}</h1>

<form method="POST" action=".">
{% csrf_token %}

{{ form|crispy }}

<div class"form-group">
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</div>
</form>
{% endblock %}