dm/urls.py
from django.conf.urls import patterns, url

from dm.views import *

urlpatterns = patterns("dm.views",
	url(r'^$', DocumentListView.as_view(), name='dm_document_list'),
	url(r'^document/create/$',
		DocumentCreateView.as_view(),
		name='dm_document_create'
	),
	url(r'^document/edit/(?P<pk>\d+)/$',
		DocumentUpdateView.as_view(),
		name='dm_document_update'
	),
)

pm/urls.py
from django.conf.urls import patterns, url
from django.views.generic import ListView, DetailView

from pm.forms import ProjectForm, PartForm
from pm.models import *
from pm.views import *

urlpatterns = patterns("pm.views",
    url(r'^$',
		ProjectListView.as_view(),
		name="pm_project_list"
	),
	url(r'^sector/list/$',
		ListView.as_view(
			model=Sector,
			paginate_by=10,
			context_object_name="sector_list"
		),
		name="pm_sector_list"
	),
	url(r'^sector/detail/(?P<pk>\d+)/$',
		DetailView.as_view(
			model=Sector,
			context_object_name="sector"
		),
		name="pm_sector_detail"
	),
	url(r'^sector/edit/(?P<pk>\d+)/$',
		SectorUpdateView.as_view(),
		name="pm_sector_edit"
	),
	url(r'^sector/create/$',
		SectorCreateView.as_view(),
		name="pm_sector_create"
	),
    url(r'^project/detail/(?P<pk>\d+)/$',
		ProjectDetailView.as_view(),
		name="pm_project_detail"
	),
    url(r'^project/report/(?P<pk>\d+)/$',
		ProjectReportView.as_view(),
		name="pm_project_report"
	),
    url(r'^project/edit/(?P<pk>\d+)/$',
		ProjectUpdateView.as_view(),
		name="pm_project_edit"
	),
	url(r'^project/create/$',
		ProjectCreateView.as_view(),
		name="pm_project_create"
	),
	url(r'^project/search/$',
		ProjectSearchView.as_view(),
		name="pm_project_search"
	),
    url(r'^project/parts/report/(?P<pk>\d+)/$',
		PartsReportView.as_view(),
		name="pm_project_parts_report"
	),
    url(r'^project/parts/cost_report/(?P<pk>\d+)/$',
		PartsCostReportView.as_view(),
		name="pm_project_parts_costreport"
	),
    url(r'^project/ce/create/(?P<pk>\d+)/$',
		CECertificateCreateView.as_view(),
		name="pm_ce_certificate_create"
	),
    url(r'^ce/detail/(?P<pk>\d+)/$',
		CECertificatePdfView.as_view(),
		name="pm_ce_certificate_detail"
	),
    url(r'^machine/detail/(?P<pk>\d+)/$',
		MachineDetailView.as_view(),
		name="pm_machine_detail"
	),
    url(r'^machine/barcode/(?P<pk>\d+)/$',
		machine_barcode,
		name="pm_machine_barcode"
	),
    url(r'^machine/parts/(?P<pk>\d+)/$',
		MachinePartsView.as_view(),
		name="pm_machine_parts"
	),
    url(r'^machine/parts/report/(?P<pk>\d+)/$',
		MachinePartsReportView.as_view(),
		name="pm_machine_parts_report"
	),
    url(r'^machine/interventions/(?P<pk>\d+)/$',
		MachineInterventionsView.as_view(),
		name="pm_machine_interventions"
	),
    url(r'^machine/edit/(?P<pk>\d+)/$',
		MachineUpdateView.as_view(),
		name="pm_machine_edit"
	),
    url(r'^machine/delete/(?P<pk>\d+)/$',
		MachineDeleteView.as_view(),
		name="pm_machine_delete"
	),
	url(r'^machine/fromcontract/(?P<pk>\d+)/$',
		MachineFromContractItem.as_view(),
		name="pm_machine_from_contract_item"
	),
    url(r'^comment/create/$',
		MachineCommentCreateView.as_view(),
		name="pm_machinecomment_create"
	),
	url(r'^comment/delete/(?P<pk>\d+)/$',
		MachineCommentDeleteView.as_view(),
		name="pm_machinecomment_delete"
	),
	url(r'^part/edit/(?P<pk>\d+)/$',
		PartUpdateView.as_view(),
		name="pm_part_edit"
	),
	url(r'^part/delete/(?P<pk>\d+)/$',
		PartDeleteView.as_view(),
		name="pm_part_delete"
	),
	url(r'machine/copy_parts/(?P<pk>\d+)/',
		CopyPartsView.as_view(),
		name="pm_copy_parts"
	),
	url(r'^part/create/$', 'create_part', name="pm_part_create"),
	url(r'^machine/create/$', 'create_machine', name="pm_machine_create"),
	url(r'^machine_ids/(?P<pk>\d+)/$', 'get_machine_ids',name="pm_machine_ids"),
	url(r'^ticket/list/$',
		TicketListView.as_view(),
		name='pm_ticket_list'
	),
	url(r'^ticket/list/(?P<pk>\d+)/',
		ProjectTicketListView.as_view(),
		name='pm_project_ticket_list'
	),
	url(r'^ticket/detail/(?P<pk>\d+)/$',
		TicketDetailView.as_view(),
		name="pm_ticket_detail"
	),
	url(r'^ticket/status/(?P<pk>\d+)/$',
		TicketStatusUpdateView.as_view(),
		name="pm_ticket_status_update"
	),
    url(r'^ticket/create/(?P<pk>\d+)/$',
		TicketCreateView.as_view(),
		name="pm_ticket_create"
	),
    url(r'^ticketitem/create/$',
		TicketItemCreateView.as_view(),
		name="pm_ticketitem_create"
	),
    url(r'^intervention/create/(?P<pk>\d+)/$',
		InterventionCreateView.as_view(),
		name="pm_intervention_create"
	),
    url(r'^intervention/edit/(?P<pk>\d+)/$',
		InterventionUpdateView.as_view(),
		name="pm_intervention_update"
	),
    url(r'^intervention/import/$',
        import_interventions,
        name="pm_intervention_import"
    ),
)

pm/models.py
import os

from PIL import Image
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

from model_utils.managers import PassThroughManager

from pm import querysets
from crm.models import Company, ContractItem
from wm.models import Article
from profiles.models import Employee

class Sector(models.Model):
    code = models.CharField(_("code"), max_length=3, unique=True)
    description = models.CharField(_("description"), max_length=50)

    class Meta:
        verbose_name = _("sector")
        verbose_name_plural = _("sectors")

    def __unicode__(self):
        return self.description

    @models.permalink
    def get_absolute_url(self):
        return ('pm_sector_detail', [self.id])

def project_thumbnail(instance, filename):
    return os.path.join("thumbnails", "%s.jpg" % instance.serial)

class Project(models.Model):
    sector = models.ForeignKey(Sector, verbose_name=_("sector"))
    serial = models.CharField(_("serial number"), max_length=4)
    old_model = models.CharField(_("old model"), max_length=5,
        blank=True, null=True)
    description = models.CharField(_("description"), max_length=255)
    notes = models.TextField(_("notes"), blank=True, null=True)
    is_retired = models.BooleanField(_("retired"), default=False)
    hide = models.BooleanField(_("hide from dashboard"), default=False)
    created_on = models.DateField(_("created on"), auto_now_add=True, null=True)
    company = models.ForeignKey(Company, verbose_name=_("company"))
    thumbnail = models.ImageField(_("thumbnail"), upload_to=project_thumbnail, null=True, blank=True)

    class Meta:
        verbose_name = _("project")
        verbose_name_plural = _("projects")
        ordering = ["-serial",]

    def __unicode__(self):
        if self.old_model:
            return u"%(model)s-%(serial)s" % {'model': self.old_model,
                                            'serial': self.serial,}
        return u"%(sector)s-%(serial)s" % {'sector': self.sector.code,
                                            'serial': self.serial,}

    @models.permalink
    def get_absolute_url(self):
        return ('pm_project_detail', [self.id])

    def save(self, force_insert=False, force_update=False):
        super(Project, self).save(force_insert, force_update)
        if self.thumbnail:
            pw = self.thumbnail.width
            ph = self.thumbnail.height
            ## max height = 240px
            if ph > 240:
                height = 240
                width = int(pw * 240.0 / ph)
                filename = str(self.thumbnail.path)
                im = Image.open(filename)
                im = im.resize((width, height), Image.ANTIALIAS)
                im.save(self.thumbnail.path)

class Machine(models.Model):
    model = models.CharField(_("model"), max_length=3)
    number = models.CharField(_("number"), max_length=2)
    description = models.CharField(_("description"), max_length=255)
    created_on = models.DateField(_("created on"), auto_now_add=True, null=True)
    finished_on = models.DateField(_("finished on"), null=True, blank=True)
    shipped_on = models.DateField(_("shipped on"), null=True, blank=True)
    running_on = models.DateField(_("running on"), null=True, blank=True)
    estimated_delivery_on = models.DateField(_("estimated delivery"), null=True, blank=True)
    is_retired = models.BooleanField(_("retired"), default=False)
    project = models.ForeignKey(Project, verbose_name=_("project"))
    contract_item = models.ForeignKey(ContractItem,
        verbose_name=_("contract item"), blank=True, null=True)

    objects = PassThroughManager.for_queryset_class(querysets.MachineQuerySet)()
    
    class Meta:
        ordering = ['number',]
        unique_together = [('number', 'project'),]
        verbose_name = _("machine")
        verbose_name_plural = _("machines")

    def __unicode__(self):
        return u"%(model)s%(number)s" % {'model': self.model,
                    'number': self.number }

    def save(self, *args, **kwargs):
        if not self.pk and not self.number:
            try:
                n = int(Machine.objects.filter(
                    project=self.project).order_by("-number")[0].number)
            except IndexError:
                n = 0
            self.number = str(n + 1).zfill(2)
        if self.shipped_on and not self.finished_on:
            self.finished_on = self.shipped_on
        return super(Machine, self).save(*args, **kwargs)

    @property
    def full_reference(self):
        return u"%s-%s" % (self.project, self)

    @models.permalink
    def get_absolute_url(self):
        return ('pm_machine_detail', [self.id])

    @property
    def contract_url(self):
        if self.contract_item:
            print self.contract_item.contract.get_absolute_url()
            return self.contract_item.contract.get_absolute_url()
        return None

class MachineComment(models.Model):
    machine = models.ForeignKey(Machine, verbose_name=_("machine"))
    body = models.TextField(_("body"))
    created_on = models.DateField(_("created on"), auto_now_add=True)
    author = models.ForeignKey(User, verbose_name=_("author"))

    class Meta:
        verbose_name = _("machine comment")
        verbose_name_plural = _("machine comments")

    def __unicode__(self):
        return self.body

class Part(models.Model):
    article = models.ForeignKey(Article, verbose_name=_("article"))
    machine = models.ForeignKey(Machine, verbose_name=_("machine"))
    quantity = models.FloatField(_("quantity"))
    function = models.CharField(_("function"), max_length=255)

    objects = PassThroughManager.for_queryset_class(querysets.PartQuerySet)()

    class Meta:
        ordering = ["pk",]
        verbose_name = _("part")
        verbose_name_plural = _("parts")

    def __unicode__(self):
        return unicode(self.article)

@receiver(post_save, sender=Part)
def decrease_stock(sender, instance, created, raw, using, **kwargs):
    if created:
        instance.article.update_stock (-1 * instance.quantity)

class CECertificate(models.Model):
    project = models.ForeignKey(Project, verbose_name=_("project"))
    date = models.DateField(_("date"))

    class Meta:
        verbose_name = _("CE certificate")
        verbose_name_plural = _("CE certificates")

    def __unicode__(self):
        return unicode(self.project)

TICKET_STATUS = (
    (0, _("The customer is waiting for an answer")),
    (1, _("Waiting for an answer from the customer")),
    (2, _("Closed")),
)

class Ticket(models.Model):
    project = models.ForeignKey(Project, verbose_name=_("project"))
    created_on = models.DateTimeField(_("created on"), auto_now_add=True)
    updated_on = models.DateTimeField(_("updated on"), auto_now=True)
    updated_by = models.ForeignKey(User, verbose_name=_("updated by"))
    status = models.PositiveIntegerField(_("status"), default=0,
        choices=TICKET_STATUS)
    summary = models.CharField(_("summary"), max_length=255)
    content = models.TextField(_("content"))

    class Meta:
        verbose_name = _("ticket")
        verbose_name_plural = _("tickets")
        ordering = ['-updated_on',]

    def __unicode__(self):
        return self.summary

    @models.permalink
    def get_absolute_url(self):
        return ('pm_ticket_detail', [self.id])

class TicketItem(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_("ticket"))
    created_on = models.DateTimeField(_("created on"), auto_now_add=True)
    created_by = models.ForeignKey(User, verbose_name=_("created_by"))
    content = models.TextField(_("content"))

    class Meta:
        verbose_name = _("ticket item")
        verbose_name_plural = _("ticket items")
    
    def __unicode__(self):
        return u"%s" % self.pk

##
## Classes to control the work hours for each project
##

class Intervention(models.Model):
    """
    An Intervention is a continuous period of time that an Employee has been
    working on a Machine.
    """
    employee = models.ForeignKey(Employee, verbose_name=_("employee"))
    machine = models.ForeignKey(Machine, verbose_name=_("machine"))
    start_at = models.DateTimeField(_("start at"))
    end_at = models.DateTimeField(_("end at"), null=True, blank=True)
    seconds = models.PositiveIntegerField(_("seconds"), editable=False,
            default=0)

    class Meta:
        verbose_name = _("intervention")
        verbose_name_plural = _("interventions")

    def __unicode__(self):
        return u"%s (%s seconds)" % (self.pk, self.seconds)

    def save(self, force_insert=False, force_update=False):
        if self.end_at:
            s = self.end_at - self.start_at
            if s.seconds > 0:
                self.seconds = s.seconds
        super(Intervention, self).save(force_insert, force_update)

    @property
    def hours(self):
        return self.seconds / 3600.

pm/templates/pm/copy_parts.html
{% extends 'pm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Copy parts" %}{% endblock %}

{% block content %}

<h1>{% trans "Copy parts" %}</h1>

<p>{% blocktrans %}Select the parts that you want to copy. The parts will be copied with the same quantities and function.{% endblocktrans %}</p>
<p>{% trans "The parts will be copied to" %} {{ machine.full_reference }}</p> 

<form method="post" action="{% url 'pm_copy_parts' machine.id %}?machine_id={{ machine_from }}">{% csrf_token %}

{{ form|crispy }}
<div>
<button type="submit" class="btn btn-primary">{% trans "Copy" %}</button>
</div>

</form>

{% endblock %}

pm/templates/pm/intervention_import.html
{% extends 'pm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "Import interventions" %}{% endblock %}

{% block content %}

<h1>{% trans "Import interventions" %}</h1>

<form method="POST" action="." enctype="multipart/form-data">
{% csrf_token %}

{{ form|crispy }}
<div class="form-group">
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
</form>
{% endblock %}

pm/templates/pm/machine_confirm_delete.html
{% extends 'pm/base.html' %}
{% load i18n %}

{% block title %}{% trans "Delete machine" %}{% endblock %}

{% block content %}

<h1>{% trans "Delete confirmation" %}</h1>

<p>{% blocktrans %}The machine {{ object }} and all its parts and comments will be deleted. Are you sure?{% endblocktrans %}</p>

<p><a href="{% url 'pm_project_detail' object.project.id %}">{% trans "Go back." %}</a>

<form action="" method="post">{% csrf_token %}
	<button type="submit" class="btn btn-primary">{% trans "Delete" %}</button>
</form>

{% endblock %}

pm/templates/pm/machine_interventions.html
{% extends "pm/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load pm_tags %}

{% block title %}{% trans "Interventions list" %}{% endblock %}

{% block content %}

<h1>{% blocktrans with machine.full_reference as reference %}Interventions in {{ reference }}{% endblocktrans %}</h1>
<p>
<a href="{% url 'pm_machine_detail' machine.id %}">{% trans "Machine details" %}</a> |
<a href="{% url 'pm_intervention_create' machine.id %}">{% trans "Add intervention" %}</a>
</p>

<div class="panel panel-primary">
<div class="panel-heading">{% trans "Interventions" %}</div>
<div class="panel-body">
    <table class="table table-striped table-hover">
    <thead>
    <tr>
        <th>{% trans "Date" %}</th>
        <th>{% trans "Hours" %}</th> 
        <th>{% trans "Employee" %}</th> 
        <th>{% trans "Actions" %}</th> 
    </tr>
    </thead>
    <tbody>
    {% for i in machine.intervention_set.all %}
    <tr>
        <td>{{ i.start_at|date:"SHORT_DATE_FORMAT" }}</td>
        <td>{{ i.seconds|as_hours:1 }}</td>
        <td>{{ i.employee.display }}</td>
        <td><a href="{% url 'pm_intervention_update' i.id %}">{% trans "Edit" %}</a></td>
    </tr>
    {% endfor %}
    </tbody>
    </table>

</div>

{% endblock %}

pm/templates/pm/machine_parts.html
{% extends "pm/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load mptt_tags %}
{% load crispy_forms_tags %}
{% load cache %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'vakata-jstree/themes/default/style.min.css' %}" />
<script src="{% static 'vakata-jstree/jstree.min.js' %}"></script>
<script>
$(function() {
	$('#tree').on('changed.jstree', function(e, data) {
		var obj = data.selected;
		var group_id = obj[0].substr(5);
		$.getJSON("/wm/group/" + group_id + "/articles/", function(data){
			var tbl_body = "";
			$.each( data, function() {
				var row = '<tr';
				if (this.enabled == false) {
					row += ' class="disabled"';
				}
                                row += '>';
				row += '<td><input name="article" type="radio" value="' + this.pk + '"/></td>'; 
                                row += '<td>';
                                if (this.favorited == false) {
                                    row += '<img src="/static/img/fav-no.png">';
                                }
                                else {
                                    row += '<img src="/static/img/fav-yes.png">';
                                }
                                row += '</td>';
				row += '<td><a href="' + this.url + '">' + this.code + '</a></td>';
				row += "<td>" + this.brand + "</td>";
				row += "<td>" + this.description + "</td>";
				row += "</tr>";
				tbl_body += row;
			});
			$("#articles tbody").html(tbl_body);
		})
		.fail(function(){
			alert("Error: No se ha podido cargar la lista de artículos.");
		});
	});
});

$(function() {
	$('#tree').jstree({
		"core" : {
			"multiple" : false,
		}
	});
});

$(function() {
	var frm =$("#part_form");
	frm.submit(function(ev) {
		var data = frm.serialize();
		console.log(data);
		$.ajax({
			type: frm.attr('method'),
			url: frm.attr('action'),
			data: data,
			success: function(data) {
				var row = "<tr>";
				row += '<td>' + data.quantity + '</td>';
				row += '<td>' + data.unit + '</td>';
				row += '<td><a href="' + data.detail_url + '">';
				row += data.reference + '</a></td>';
				row += '<td>' + data.description + '</td>';
				row += '<td>' + data.function + '</td>';
				row += '<td>';
				row += '<a href="' + data.edit_url;
				row += '" class="btn btn-xs btn-primary">{% trans "Edit" %}</a> ';
				row += '<a href="' + data.delete_url;
				row += '" class="btn btn-xs btn-danger">{% trans "Delete" %}</a>';
				row += '</td>';
				row += "<tr>";
				$('#parts tr:last').after(row);
			},
			error: function(resp) {
				var errors = JSON.parse(resp.responseText);
				alert("Error. Comprueba el formulario.");
			}
		});
		ev.preventDefault();
	});
});
</script>

{% endblock %}

{% block title %}{% trans "Parts in" %} {{ machine.project }}-{{ machine.model }}{{ machine.number }}{% endblock %}

{% block content %}

<h1>{% trans "Parts in" %} {{ machine.project }}-{{ machine.model }}{{ machine.number }}</h1>
<p>
<a href="{% url 'pm_project_detail' machine.project.id %}">{{ machine.project }}</a>
|
<a href="#" id="toggle-import">{% trans "Import" %}</a>
</p>

<div class="panel panel-primary" id="import-panel" style="display: none">
<div class="panel-heading">{% trans "Copy from another machine" %}</div>
<div class="panel-body">
<form method="get" action="{% url 'pm_copy_parts' machine.id %}">
{{ import_form|crispy }}
<div>
<button type="input" class="btn btn-primary btn-sm">{% trans "Next" %}</button>
</div>
</form>
</div>
</div>

<table id="parts" class="table table-striped table-hover">
<thead>
<tr>
<th>{% trans "Qty" %}</th>
<th>{% trans "Unit" %}</th>
<th>{% trans "Reference" %}</th>
<th>{% trans "Description" %}</th>
<th>{% trans "Function" %}</th>
<th>{% trans "Actions" %}</th>
</tr>
</thead>
<tbody>
{% for part in machine.part_set.all %}
<tr>
<td>{{ part.quantity|floatformat:"0" }}</td>
<td>{{ part.article.measure_unit }}</td>
<td><a href="{% url 'wm_article_detail' part.article.id %}">{{ part.article.code }}</a></td>
<td>{{ part.article.description }}</td>
<td>{{ part.function }}</td>
<td>
<a href="{% url 'pm_part_edit' part.id %}" class="btn btn-xs btn-primary">{% trans "Edit" %}</a>
<a href="{% url 'pm_part_delete' part.id %}" class="btn btn-xs btn-danger">{% trans "Delete" %}</a>
</td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="col-md-4">
<div class="panel panel-primary">
<div class="panel-heading">{% trans "Select category" %}</div>
<div id="tree" class="panel-body">
{% cache 1800 groups_tree %}
<ul>
	{% recursetree nodes %}
		<li id="node_{{ node.id }}">
			{{ node.name }}
			{% if not node.is_leaf_node %}
				<ul class="children">
					{{ children }}
				</ul>
			{% endif %}
		</li>
	{% endrecursetree %}
</ul>
{% endcache %}
</div>
</div>
</div>

<div class="col-md-8">
<div class="panel panel-primary">
<div class="panel-heading">{% trans "Select article" %}</div>
<div id="article_selection" class="panel-body">

<form id="part_form" method="POST" action="{% url 'pm_part_create' %}" class="form-inline">{% csrf_token %}
<input type="hidden" name="machine" value="{{ machine.id }}"/>
  <div class="form-group">
    <label class="sr-only" for="id_quantity">{% trans "Quantity" %}</label>
	<input id="id_quantity" type="text" name="quantity" class="form-control" placeholder="{% trans "Quantity" %}" style="width: 6em" />
  </div>
  <div class="form-group">
    <label class="sr-only" for="id_funcion">{% trans "Funcion" %}</label>
    <input id="id_function" type="text" name="function" class="form-control" placeholder="{% trans "Function" %}" style="width: 30em" />
  </div>
<button type="submit" class="btn btn-primary">{% trans "Save" %}</button>


<table id="articles" class="table table-striped table-hover">
<thead>
<th>&nbsp;</th>
<th>&nbsp;</th>
<th>{% trans "Reference" %}</th>
<th>{% trans "Brand" %}</th>
<th>{% trans "Description" %}</th>
</thead>
<tbody></tbody>
</table>
</form>
</div>
</div>

</div>
</div>

<script>
$(function() {
	$('#tree').jstree(true).select_node('child_node');
	$('#toggle-import').click(function() {
		$('#import-panel').toggle();
	});
	$('#id_project').change(function() {
		var project = $(this).val();
		$.getJSON("/pm/machine_ids/" + project, function(data){
			var opt = '';
			$.each(data, function() {
				opt += '<option value="';
				opt += this.pk;
				opt += '">';
				opt += this.fields.description;
				opt += '</option>';
			});
			$('#id_machine_id').html(opt);
		});
		
	});
});
</script>

{% endblock %}

pm/templates/pm/machinecomment_form.html
{% extends 'pm/base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}{% trans "New comment" %}{% endblock %}

{% block content %}

<h1>{% trans "New comment" %}</h1>

<form method="POST" action="." class="uniForm">
{% csrf_token %}

{{ form|crispy }}
<p><input type="submit" value="{% trans "Save" %}" /></p>
</form>
{% endblock %}

pm/templates/pm/parts_pdf.html
{% extends 'pdf_base.html' %}
{% load i18n %}

{% block content %}

<h1>{{ project }}</h1>
<h2>{% trans "Parts report" %}</h2>

{% for machine in project.machine_set.all %}

<h3>{{ machine }}: {{ machine.description }}</h3>
<table border="1">
<thead>
<tr>
<th style="width: 10%">{% trans "Quantity" %}</th>
<th>{% trans "Reference" %}</th>
<th>{% trans "Description" %}</th>
<th>{% trans "Function" %}</th>
</tr>
</thead>
<tbody>
{% for part in machine.part_set.all %}
	<tr>
	<td style="text-align: center">{{ part.quantity }}</td>
	<td>{{ part.article.code }}</td>
	<td>{{ part.article.description }}</td>
	<td>{{ part.function }}</td>
	</tr>
{% endfor %}
</tbody>
</table>


{% endfor %}


{% endblock %}

pm/templates/pm/ticket_list.html
{% extends "pm/base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Tickets" %}{% endblock %}

{% block content %}

{% if project %}
<h1>{% trans "Tickets for" %} {{ project }}</h1>

<p>
<a href="{% url 'pm_ticket_create' project.id %}">{% trans "New ticket" %}</a>
</p>
{% else %}
<h1>{% trans "All the tickets" %}</h1>
{% endif %}

<table class="table table-striped table-hover">
<thead>
<tr>
    {% if not project %}<th>{% trans "Project" %}</th>{% endif %}
    <th>{% trans "Summary" %}</th>
    <th>{% trans "Updated on" %}</th>
	<th>{% trans "Updated by" %}</th>
    <th>{% trans "Status" %}</th>
</tr>
</thead>
<tbody>
{% for ticket in ticket_list %}
{% if ticket.status == 0 %}
<tr class="danger">
{% elif ticket.status == 1 %}
<tr class="warning">
{% else %}
<tr>
{% endif %}
	{% if not project %}
	<td><a href="{% url 'pm_project_detail' ticket.project.id %}">{{ ticket.project }}</a><td>
	{% endif %}
	<td><a href="{% url 'pm_ticket_detail' ticket.id %}">{{ ticket.summary }}</a></td>
	<td>{{ ticket.updated_on }}</td>
	<td>{{ ticket.updated_by }}</td>
	<td>{{ ticket.get_status_display }}</td>
</tr>
{% endfor %}
</tbody>
</table>

<div class="pager">
	<ul>
		{% if page_obj.has_previous %}
		<li>
			<a href="?page={{ page_obj.previous_page_number }}">{% trans "Previous" %}</a>
		</li>
		{% endif %}
		{% if page_obj.has_next %}
		<li>
			<a href="?page={{ page_obj.next_page_number }}">{% trans "Next" %}</a>
		</li>
		{% endif %}
	</ul>
</div>

{% endblock %}